vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.smartindent = true
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "80"
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.syntax = 'off'
vim.opt.wildmode = 'longest,list'
vim.opt.mouse = ''
vim.opt.foldmethod = 'indent'
vim.opt.foldcolumn = '1'
vim.opt.history = 10000
vim.g.netrw_banner = 0
vim.g.neoformat_haskell_ormolu = { exe = 'ormolu', args = {}}
vim.g.neoformat_enabled_haskell = {'sortimports', 'ormolu' }
vim.opt.ignorecase = true
vim.opt.smartcase = true
